In [1]:
import pyreadr as pyr
import pandas as pd
import numpy as np
import pyranges as pr
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from statistics import median
import math

In [2]:
ctcf = pyr.read_r("CTCF.rds")
stat = pyr.read_r("STAT3.rds")
ets = pyr.read_r("ETS1.rds")
myod = pyr.read_r("MYOD1.rds")
fosl = pyr.read_r("FOSL2.rds")

In [3]:
ctcf = ctcf[None]
stat = stat[None]
ets = ets[None]
myod = myod[None]
fosl = fosl[None]

In [6]:
ctcf

,accessibility,DNAme,H2az,H3k27ac,H3k27me3,H3k36me3,H3k4me1,H3k4me2,H3k4me3,H3k79me2,H3k9ac,H3k9me3,H4k20me1,phylop,LLR,tfbs
rownames,,,,,,,,,,,,,,,,
CTCF_46229,0.0,438,12.1,0.0,36.7,7.1,28.7,14.0,22.7,0.0,13.6,2.0,32.2,1.720,47,1
CTCF_965,8.0,0,0.8,22.0,46.5,15.3,20.3,14.0,20.0,0.0,22.0,58.6,18.1,-1.163,23,1
CTCF_970,0.0,180,0.0,0.0,20.0,10.0,0.0,0.0,14.0,7.4,13.6,41.7,10.2,8.256,16,1
CTCF_971,0.0,192,0.0,0.0,20.0,10.0,0.0,0.0,14.0,9.4,20.6,40.5,10.0,5.922,11,1
CTCF_972,8.0,122,8.0,0.0,0.0,1.5,0.0,0.0,22.0,8.0,34.0,52.8,12.8,10.303,46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CTCF_46239,0.0,183,27.8,0.0,0.0,16.0,50.0,0.0,32.1,0.0,20.0,0.0,38.0,-4.710,31,0
CTCF_46240,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.766,62,0
CTCF_46241,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-4.733,41,0
CTCF_46242,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.913,16,0
CTCF_1,18.1,0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,30.0,0.0,3.944,15,0

In [4]:
def linear_regression(data, target, corrl):
    
    # y = b1 * x + b0
    
    data = data.astype(float)
    
    x = data[target].tolist()
    
    b0 = - 0.5
    
    if bool(data[target].corr(data[corrl]) > 0) is True:
        
        b1 = 1 / median(x)
        
    else: 
        
        b1 = -1 / median(x)
    
    true_positives = 0
    false_positives = 0
    true_negatives = 0
    false_negatives = 0
    
    for value in x:
        
        y = b1 * value + b0
        
        if bool(y >= 0.5 and value >= median(x)) is True:
            true_positives += 1
        elif bool(y <= 0.5 and value >= median(x)) is True:
            false_negatives += 1
        elif bool(y <= 0.5 and value <= median(x)) is True:
            true_negatives += 1
        else:
            false_negatives += 1
            
    return [true_positives, false_positives, true_negatives, false_negatives]

In [5]:
bismillah = linear_regression(ctcf, "LLR", "tfbs")
bismillah

KeyboardInterrupt:

In [ ]:
def logistic_regression(data, target, corrl):
    
    # y = b1 * x + b0
    
    data = data.astype(float)
    
    x = data[target].tolist()
    
    b0 = - 0.5
    
    if bool(data[target].corr(data[corrl]) > 0) is True:
        
        b1 = 1 / median(x)
        
    else: 
        
        b1 = -1 / median(x)
    
    true_positives = 0
    false_positives = 0
    true_negatives = 0
    false_negatives = 0
    
    for value in x:
        
        y = 1 / 1 + math.exp(-(b1 * value + b0))
        
        if bool(y >= 0.5 and value >= 0.5 * median(x)) is True:
            true_positives += 1
        elif bool(y <= 0.5 and value >= 0.5 * median(x)) is True:
            false_negatives += 1
        elif bool(y <= 0.5 and value <= 0.5 * median(x)) is True:
            true_negatives += 1
        else:
            false_negatives += 1
            
    return [true_positives, false_positives, true_negatives, false_negatives]

In [ ]:
logistic_bismillah = logistic_regression(ctcf, "LLR", "tfbs")
logistic_bismillah

In [ ]:
a = 3
bool(a < 6 and a < 7)

In [ ]:
type(ctcf["LLR"][1])

In [ ]:
1 / 1 + math.exp(-0.5)